// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_hero: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  description_slice: dynamic(() => import("./DescriptionSlice")),
  hero: dynamic(() => import("./Hero")),
  home_services: dynamic(() => import("./HomeServices")),
  rich_text_slice: dynamic(() => import("./RichTextSlice")),
};
